### ISSUE TITLE
[be2-scala] Cleanup progress

### ISSUE THREAD

**Issue by RaulinN** [dedis/popstellar#792]
# Scala Spring 2022 Cleanup progress

- Supervisor: @pierluca 
- TAs responsible: @tuomas-p @GabrielFleischer @RaulinN 

## TODO / in progress
- [ ] chained `await` removal/simplification using `flatmap` [link](https://stackoverflow.com/questions/19045936/scalas-for-comprehension-with-futures)
- [ ] registry upgrade:
  - add election messages in the builder module
  - refactor `ParamsWithMessageHandler` accordingly
- [ ] refactor DB cache
- [ ] reduce overall code complexity (e.g. triple `match` in `SocialMediaHandler`)
- [ ] find a way to simplify/remove typed `JsonRpcRequest` (`model/network/requests`)
- [ ] check that the doc (e.g. guide) is up-to-date

## Future work (if time permits)
-

## Starting tasks kept for Spring 2022 students 
-

## Removed
- Update the project to Scala 3 (akka does not fully support scala 3 as of yet)
